[build-system]
requires      = ["hatchling>=1.25"]
build-backend = "hatchling.build"

[project]
name            = "Argos"
version         = "1.2.0"
description     = "The Many Eyed Sentinel"
authors         = [{ name = "Dr4gnf1y", email = "shadowburner@protonmail.com" }]
readme          = "README.md"
requires-python = ">=3.9,<3.13"

dependencies = [
  "torch==2.3.*",
  "torchvision==0.18.*",
  "ultralytics>=8.0",

  "onnxruntime==1.19.2 ; python_version < '3.10'",
  "onnxruntime>=1.22,<1.24 ; python_version >= '3.10'",
  "onnx>=1.18",

  "opencv-python-headless>=4.10,<4.12",
  "numpy<2.1",
  "pillow>=10.0,<12.0",
  "pillow-avif-plugin>=1.4",

  "matplotlib",
  "scipy>=1.11",
  "pandas",
  "redis>=5.0",

  "typer>=0.12",
]

[project.optional-dependencies]
dev = [
  "pytest",
  "pytest-cov",
  "black",
  "isort",
  "ruff",
  "pre-commit",

  "boto3",
  "moto[all] ~= 4.2",
]

[project.scripts]
target  = "panoptes.cli:main"
argos   = "panoptes.cli:main"

d       = "panoptes.cli:main_detect"
detect  = "panoptes.cli:main_detect"
hm      = "panoptes.cli:main_heatmap"
heatmap = "panoptes.cli:main_heatmap"
gj      = "panoptes.cli:main_geojson"
geojson = "panoptes.cli:main_geojson"
all     = "panoptes.cli:main_all"

[tool.hatch.build]
include = [
  "panoptes/**/*.py",
  "panoptes/assets/*",
]
exclude = [
  "panoptes/model/*.onnx",
]

[tool.pytest.ini_options]
addopts   = "-q"
testpaths = ["tests"]

[tool.black]
line-length = 100

[tool.isort]
profile           = "black"
line_length       = 100
force_single_line = true

[tool.ruff]
line-length = 100
