# .github/workflows/_project-template.yml
name: Deploy Monorepo Project

on:
  workflow_call:
    inputs:
      project-dir:
        description: "Path like projects/argos"
        required: true
        type: string

permissions:
  id-token: write # OIDC → AWS
  contents: read  # repo checkout

env:
  AWS_REGION: us-east-1 # change if you deploy elsewhere

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # ────────────────────────────────────────────────────────────────
      # 0) Checkout – WITH Git-LFS model weights
      # ────────────────────────────────────────────────────────────────
      - name: Check out source
        uses: actions/checkout@v4
        with:
          lfs: true

      # ────────────────────────────────────────────────────────────────
      # 1) AWS creds via OIDC
      # ────────────────────────────────────────────────────────────────
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::211125358149:role/TreadSoftlyAWS-GHA-OIDC
          aws-region: ${{ env.AWS_REGION }}

      # ────────────────────────────────────────────────────────────────
      # 2) CDK CLI
      # ────────────────────────────────────────────────────────────────
      - name: Install CDK CLI
        run: npm install -g aws-cdk@2

      # ────────────────────────────────────────────────────────────────
      # 3) CDK deploy (CDK builds the Docker asset itself)
      # ────────────────────────────────────────────────────────────────
      - name: Install Python deps for CDK app
        working-directory: ${{ inputs.project-dir }}
        run: pip install --quiet aws-cdk-lib constructs

      - name: CDK synth
        working-directory: ${{ inputs.project-dir }}
        run: cdk synth

      - name: CDK deploy
        working-directory: ${{ inputs.project-dir }}
        run: cdk deploy --require-approval never
