name: Argos CI/CD

on:
  push:
    paths:
      - "projects/argos/**"
      - ".github/workflows/argos.yml"

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    uses: ./.github/workflows/_project-template.yml
    with:
      project-dir: projects/argos
