name: Argos CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: ["3.9", "3.12"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Pull Git LFS
        run: git lfs pull

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Upgrade pip & install
        run: |
          python -m pip install --upgrade pip
          pip install -e "projects/argos[dev]"

      - name: Run tests (fast weights)
        env:
          panoptes_TEST_DET_WEIGHTS: projects/argos/panoptes/model/yolov8n.onnx
          panoptes_TEST_SEG_WEIGHTS: projects/argos/panoptes/model/yolov8n-seg.onnx
        run: pytest -q projects/argos/tests
