# .github/workflows/drone-vision.yml  (same change for ci.yml & _project-template.yml)
name: Drone‑Vision CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: ["3.9", "3.12"]

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install package
        run: |
          python -m pip install --upgrade pip
          pip install -e projects/drone-vision[dev]

      # ──────────────────────────────────────────────────────────────
      # point pytest at the *real* test directory
      # ──────────────────────────────────────────────────────────────
      - name: Unit tests
        run: pytest -q projects/drone-vision/tests
