name: Argos CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: ["3.9", "3.12"]

    steps:
      - name: Checkout (no LFS)
        uses: actions/checkout@v4
        with:
          lfs: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: pip
          cache-dependency-path: |
            projects/argos/pyproject.toml
            projects/argos/requirements.txt
            projects/argos/constraints.txt

      - name: Install project (editable)
        run: |
          python -m pip install --upgrade "pip<25.3"
          pip install -e "projects/argos[dev]" -c projects/argos/constraints.txt
          pip check

      - name: Warm models (nano)
        env:
          ARGOS_WEIGHT_PRESET: nano
          PYTHONUTF8: "1" # safe cross-OS, fixes Windows charmap
        run: python projects/argos/bootstrap.py --ensure --yes

      - name: Run tests
        env:
          panoptes_TEST_DET_WEIGHTS: projects/argos/panoptes/model/yolov8n.onnx
          panoptes_TEST_SEG_WEIGHTS: projects/argos/panoptes/model/yolov8n-seg.onnx
        run: pytest -q projects/argos/tests -vv
