name: Drone-Vision CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: ["3.9", "3.12"]

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true # pulls the .onnx weights

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install package
        run: |
          python -m pip install --upgrade pip
          pip install projects/drone-vision[dev]

      - name: Unit tests
        run: pytest -q projects/drone-vision/tests
